
"use client"

import { Suspense, useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Search, ArrowUpRight, Filter, Plus } from "lucide-react"
import { gsap } from "gsap"
import { CommunityGrid } from "@/components/community-grid"
import { UploadModal } from "@/components/upload-modal"
import { cn } from "@/lib/utils"

import { useAuth } from "@/context/auth-context"
import { useRouter, useSearchParams } from "next/navigation"

function CommunityContent() {
  const headerRef = useRef<HTMLDivElement>(null)
  const [isUploadOpen, setIsUploadOpen] = useState(false)
  const [searchValue, setSearchValue] = useState("")
  const [isFiltersVisible, setIsFiltersVisible] = useState(true)
  const { user } = useAuth()
  const router = useRouter()
  const searchParams = useSearchParams()
  const activeFilter = (searchParams.get("filter") || "").toLowerCase()
  const currentFilter = activeFilter || "all"

  const filterItems = [
    { id: "all", label: "All" },
    { id: "works", label: "Works" },
    { id: "templates", label: "Templates" },
    { id: "video", label: "Video" },
    { id: "image", label: "Image" },
    { id: "remixable", label: "Open to Remix" },
    { id: "branching", label: "Popular Branches" },
    { id: "directed", label: "Directed" },
    { id: "telegram", label: "Telegram" },
  ]

  const updateQuery = (updates: Record<string, string | null>) => {
    const params = new URLSearchParams(searchParams.toString())
    Object.entries(updates).forEach(([key, value]) => {
      if (!value) params.delete(key)
      else params.set(key, value)
    })
    const query = params.toString()
    router.replace(query ? `/community?${query}` : "/community")
  }

  const applySearch = () => {
    updateQuery({ q: searchValue.trim() || null })
  }

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.from(".hero-text", {
        y: 30,
        opacity: 0,
        duration: 0.8,
        stagger: 0.1,
        ease: "power3.out",
        force3D: true
      })

      gsap.from(".hero-controls", {
        y: 15,
        opacity: 0,
        duration: 0.6,
        delay: 0.3,
        ease: "power2.out",
        force3D: true
      })
    }, headerRef)

    return () => ctx.revert()
  }, [])

  useEffect(() => {
    setSearchValue(searchParams.get("q") || "")
  }, [searchParams])

  return (
    <main ref={headerRef} className="min-h-screen bg-[#020202] text-white selection:bg-purple-500/30 overflow-x-hidden">

      {}
      <UploadModal isOpen={isUploadOpen} onClose={() => setIsUploadOpen(false)} />

      {}
      <div className="fixed inset-0 z-0 pointer-events-none transform-gpu overflow-hidden">
        {}
        <div className="hidden md:block absolute top-[-20%] left-[20%] w-[60%] h-[60%] bg-purple-900/5 rounded-full blur-[180px] will-change-transform" />
        <div className="hidden md:block absolute bottom-[-10%] right-[-5%] w-[40%] h-[40%] bg-blue-900/5 rounded-full blur-[150px] will-change-transform" />
        {}
        <div className="md:hidden absolute top-[-10%] left-[10%] w-[80%] h-[60%] rounded-full bg-[radial-gradient(circle,rgba(88,28,135,0.15)_0%,transparent_70%)] will-change-transform" />
        <div className="md:hidden absolute bottom-[0%] right-[-10%] w-[70%] h-[50%] rounded-full bg-[radial-gradient(circle,rgba(30,58,138,0.15)_0%,transparent_70%)] will-change-transform" />
      </div>

      {}
      <section className="relative z-10 pt-48 md:pt-56 pb-12 md:pb-24 px-6 md:px-16 max-w-[2000px] mx-auto">
        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-8 md:gap-10 mb-12 md:mb-20">
          <div className="space-y-4 md:space-y-6 max-w-3xl">
            <div className="flex items-center gap-3 hero-text transform-gpu">
              <div className="h-[1px] w-8 bg-purple-500/50"></div>
              <span className="text-xs font-medium tracking-[0.3em] uppercase text-neutral-400">The Gallery</span>
            </div>
            <h1 className="text-5xl md:text-6xl lg:text-8xl font-light tracking-tight text-white hero-text leading-[1.05] md:leading-[0.9] transform-gpu">
              Community <br className="hidden md:block" />
              <span className="font-serif italic text-neutral-500">Perspectives</span>
            </h1>
            <p className="text-base md:text-lg text-neutral-400 max-w-xl hero-text pt-2 md:pt-4 leading-relaxed font-light transform-gpu truncate-multiline">
              A curated exhibition of visual intelligence. Generated by imagination, powered by StudioX.
            </p>
          </div>

          <div className="hero-controls w-full lg:w-auto flex flex-col sm:flex-row gap-4 items-stretch sm:items-center">
            <Button
              className="inline-flex h-14 min-w-[168px] items-center justify-center gap-3 rounded-full bg-white px-8 text-base font-medium leading-none text-black transition-all duration-300 hover:bg-neutral-200"
              onClick={() => {
                if (!user) {
                  router.push(`/login?redirect=${encodeURIComponent("/community")}`)
                  return
                }
                setIsUploadOpen(true)
              }}
            >
              <Plus className="h-4 w-4 shrink-0" />
              <span className="leading-none">Upload</span>
            </Button>
            <div className="relative group w-full sm:w-[280px]">
              <Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-500 group-hover:text-white transition-colors duration-300" />
              <Input
                placeholder="Search the gallery..."
                value={searchValue}
                onChange={(event) => setSearchValue(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === "Enter") {
                    event.preventDefault()
                    applySearch()
                  }
                }}
                className="pl-12 h-14 bg-white/[0.03] border-white/5 rounded-full text-base text-white placeholder:text-neutral-600 focus:bg-white/[0.08] focus:border-white/10 transition-all duration-300 shadow-xl"
              />
            </div>
            <Button
              variant="outline"
              size="icon"
              onClick={() => setIsFiltersVisible((current) => !current)}
              aria-pressed={isFiltersVisible}
              className={cn(
                "h-14 w-14 rounded-full border-white/5 bg-white/[0.03] transition-all duration-300",
                isFiltersVisible || currentFilter !== "all"
                  ? "border-white/15 bg-white/[0.08] text-white"
                  : "hover:bg-white/[0.08] hover:text-white hover:border-white/10"
              )}
            >
              <Filter className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div
          className={cn(
            "hero-controls overflow-hidden transition-all duration-300 ease-out",
            isFiltersVisible ? "mb-8 max-h-64 opacity-100" : "mb-0 max-h-0 opacity-0"
          )}
        >
          <div className="mb-3 flex items-center gap-3 pt-1">
            <div className="h-px w-8 bg-white/10" />
            <span className="text-[11px] font-semibold uppercase tracking-[0.28em] text-zinc-500">
              Browse Categories
            </span>
          </div>
          <div className="flex flex-wrap gap-2">
            {filterItems.map((item) => {
              const isActive = currentFilter === item.id
              return (
                <button
                  key={item.id}
                  onClick={() => updateQuery({ filter: item.id === "all" ? null : item.id })}
                  className={cn(
                    "rounded-full border px-4 py-2 text-xs font-semibold tracking-wide transition-colors",
                    isActive
                      ? "border-lime-300/40 bg-lime-300/10 text-lime-100"
                      : "border-white/10 bg-white/[0.03] text-zinc-400 hover:border-white/20 hover:text-white"
                  )}
                >
                  {item.label}
                </button>
              )
            })}
          </div>
        </div>

        {}
        <CommunityGrid />

      </section>

      {}
      <section className="relative z-10 mx-auto max-w-7xl px-4 pb-32 text-center">
        <div className="h-[1px] w-full max-w-xs mx-auto bg-gradient-to-r from-transparent via-white/10 to-transparent mb-8"></div>
        <Button
          variant="ghost"
          size="lg"
          className="gap-3 text-neutral-500 hover:text-white hover:bg-transparent rounded-full px-8 h-auto text-sm tracking-widest uppercase transition-all duration-500 group"
        >
          <ArrowUpRight className="h-3 w-3 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
        </Button>
      </section>
    </main>
  )
}

export default function CommunityPage() {
  return (
    <Suspense fallback={null}>
      <CommunityContent />
    </Suspense>
  )
}
